use_frameworks!

platform :ios, '8.0'

target 'GJHttpToolOC_Example' do
  pod 'GJHttpToolOC', :path => '../'

  target 'GJHttpToolOC_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
